server:
  port: 8088

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8090/eureka/

logging:
  level:
    org.springframework: DEBUG

management:
  endpoint:
    web:
      exposure:
        include: "*"
#Actuator

h2:
  console:
    enabled: true

spring:
  jpa:
    show-sql: true
  application:
    name: product

