apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: kwon5891/product-service:latest
          ports:
            - containerPort: 8099
          livenessProbe:
            httpGet:
              path: /
              port: 8099
